package com.springboot.simple.jdbc.model;

import java.util.Date;

public class BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base.id
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base.create_time
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base.modified_time
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base.deleted
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base.id
     *
     * @return the value of t_base.id
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base.id
     *
     * @param id the value for t_base.id
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base.create_time
     *
     * @return the value of t_base.create_time
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base.create_time
     *
     * @param createTime the value for t_base.create_time
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base.modified_time
     *
     * @return the value of t_base.modified_time
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base.modified_time
     *
     * @param modifiedTime the value for t_base.modified_time
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base.deleted
     *
     * @return the value of t_base.deleted
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base.deleted
     *
     * @param deleted the value for t_base.deleted
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}