package com.springboot.simple.jdbc.model;

public class BaseModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    protected boolean distinct;

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }
}