server:
  port: 8080


jdbc:
  master:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: 123456
  slave-list:
    - driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://127.0.0.1:3306/demo1
      username: root
      password: 123456
    - driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://127.0.0.1:3306/demo2
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.springboot.simple.model

#spring:
#  redis:
#    host: localhost
#    port: 6379
#  datasource:
#    driver-class-name: org.gjt.mm.mysql.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.0.1:3306/demo
#    username: root
#    password: 123456
#    dbcp2:
#      min-idle: 5                                           # 数据库连接池的最小维持连接数
#      initial-size: 5                                       # 初始化连接数
#      max-total: 5                                          # 最大连接数
#      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

#aliyun:
#  oss:
#    endpoint:
#    access-key-id:
#    access-key-secret:
#    support-cname: false

#    domain-name: