server:
  port: 8080


jdbc:
  master:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo
    username: root
    password: 123456
  slave-list:
    - driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://127.0.0.1:3306/demo1
      username: root
      password: 123456
    - driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://127.0.0.1:3306/demo2
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.springboot.simple.model

spring:
  redis:
    host: localhost
    port: 6379


#aliyun:
#  oss:
#    endpoint:
#    access-key-id:
#    access-key-secret:
#    support-cname: false

#    domain-name: