package com.springboot.simple.jdbc.mapper;


import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BaseModelMapper<T,E> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    int countByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    int deleteByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    List<T> selectByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    T selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    int updateByExample(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base
     *
     * @mbggenerated Thu Mar 26 20:10:23 CST 2020
     */
    int updateByPrimaryKey(T record);
}